version: "3.8"
services:
  db:
    container_name: postgres_trade
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=TRADE
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    hostname: postgres
    networks:
      - trade_network
  trader_server:
    container_name: trade_server
    image: trade-server
    build:
      context: trade-server
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
    hostname: trade-server
    networks:
      - trade_network
  keycloak:
    container_name: keycloak_trade
    image: bitnami/keycloak
    environment:
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_HOST=postgres
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_USER=admin
      - KEYCLOAK_DATABASE_PASSWORD=admin
      - KEYCLOAK_DATABASE=KEYCLOAK
    ports:
      - "8081:8080"
      - "8443:8443"
    hostname: keycloak
    depends_on:
      - db
    networks:
      - trade_network
networks:
  trade_network:
    name: trade_network
