version: "3.8"
services:
  db:
    container_name: postgres_trade
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=TRADE
    volumes:
      - ./infrastructure/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    hostname: postgres
    networks:
      - trade_network
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper
    depends_on:
      - db
    environment:
      - ZOO_PORT_NUMBER=2181
      - ZOO_ENABLE_AUTH=yes
      - ZOO_CLIENT_USER=zookeeper
      - ZOO_CLIENT_PASSWORD=zookeeper_password
      - ZOO_MAX_SESSION_TIMEOUT=30000
    volumes:
      - ./infrastructure/zookeeper:/bitnami
    hostname: zookeeper
    ports:
      - "2181:2181"
    networks:
      - trade_network
  kafka:
    container_name: kafka
    image: bitnami/kafka
    depends_on:
      - db
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ZOOKEEPER_USER=zookeeper
      - KAFKA_ZOOKEEPER_PASSWORD=zookeeper_password
      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka:9002
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9002
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
    volumes:
      - ./infrastructure/kafka_data:/bitnami
    hostname: kafka
    ports:
      - "9002:9002"
      - "9003:9003"
    networks:
      - trade_network
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui
    hostname: kafkaui
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9002
    ports:
      - "9082:8080"
    networks:
      - trade_network
  trade_server:
    container_name: trade_server
    build:
      context: trade-server
      dockerfile: src/main/docker/Dockerfile.jvm
    depends_on:
      - db
    ports:
      - "8080:8080"
    hostname: trade-server
    networks:
      - trade_network
  supplier_server:
    container_name: supplier-server
    build:
      context: supplier-server
      dockerfile: src/main/docker/Dockerfile.jvm
    depends_on:
      - db
    hostname: supplier-server
    networks:
      - trade_network
  keycloak:
    container_name: keycloak_trade
    image: bitnami/keycloak
    depends_on:
      - db
    environment:
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_HOST=postgres
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_USER=admin
      - KEYCLOAK_DATABASE_PASSWORD=admin
      - KEYCLOAK_DATABASE=KEYCLOAK
    ports:
      - "8081:8080"
      - "8443:8443"
    hostname: keycloak
    networks:
      - trade_network
networks:
  trade_network:
    name: trade_network
