version: "3.8"
services:
  db:
    container_name: postgres_trade
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=TRADE
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    hostname: postgres
    networks:
      - trade_network
  keycloak:
    container_name: keycloak_trade
    image: bitnami/keycloak
    environment:
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_HOST=postgres
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_USER=admin
      - KEYCLOAK_DATABASE_PASSWORD=admin
    ports:
      - "8080:8080"
      - "8443:8443"
    hostname: keycloak
    depends_on:
      - db
    networks:
      - trade_network
  wildfly:
    container_name: wildfly_trade
    image: bitnami/wildfly:26.1.3
    environment:
      - WILDFLY_USERNAME=admin
      - WILDFLY_PASSWORD=admin_password
      - WILDFLY_MANAGEMENT_LISTEN_ADDRESS=0.0.0.0
    ports:
      - "8081:8080"
      - "9990:9990"
    hostname: wildfly
    depends_on:
      - db
    networks:
      - trade_network
networks:
  trade_network:
    name: trade_network
