quarkus:
  http:
    root-path: /trade-service
  datasource:
    jdbc:
      url: jdbc:postgresql://postgres:5432/TRADE
    db-kind: postgresql
    username: admin
    password: admin
  hibernate-orm:
    database.generation: none

kafka:
  bootstrap:
    servers: kafka:9002

mp:
  messaging:
    incoming:
      delivery_response:
        group.id: trade_delivery_response
        auto.offset.reset: latest
        commit-strategy: throttled
        failure-strategy: fail
    outgoing:
      delivery_request:
        auto.offset.reset: latest
        commit-strategy: throttled
        failure-strategy: fail